### ISSUE TITLE
Get battery voltage documentation?

### ISSUE THREAD

**Issue by antonvh** [ddemidov/ev3dev-lang-python#11]
I can't figure out from the docs how to get the battery voltage.

This doesn't work:
``` py
ps = ev3dev.power_supply
print ps.measured_voltage
```

**Comment by ddemidov** [comment]
Will this work for you?
```py
print(ev3dev.power_supply.battery.measured_voltage)
```
I am away from my ev3 for another week, so I can not test this, sorry.

**Comment by antonvh** [comment]
It works on an Ev3. Thanks. But I'm working on a RPi. I figured out how to get the voltage earlier, before ev3dev. It's here. https://gist.github.com/antonvh/c81c247fc03029a1ba6a
Maybe you can add it to your library? Would be neat.

**Comment by ddemidov** [comment]
I don't have an RPi to test this. 

* Doesn't RPi provide an entry in `/sys/class/power-supply` for its power source? Then we could make `power_supply::battery` to point there instead of [legoev3-battery](https://github.com/ev3dev/ev3dev-lang/blob/e91926b38c8dce7707425ea2969e09d42df494f0/cpp/ev3dev.cpp#L908-L911).
* In case not, is it possible to get min and max values for voltage and also the value of current on RPi? Then we could replace the methods imported from C++ bindings with RPi-specific.

**Comment by antonvh** [comment]
Solved with issue https://github.com/ev3dev/ev3dev/issues/401
