### ISSUE TITLE
add debian package for python-ev3dev

### ISSUE THREAD

**Issue by ensonic** [ddemidov/ev3dev-lang-python#13]
I have packaged my open-roberta.org cloud ide service. The code uses python-ev3dev and now I'd like to express that in the package deps.

I think it would be good to have debian packages for the language bindings, where possible. For python-ev3dev I can give packaging a try as a PR for this repo. Sounds good?

**Comment by ddemidov** [comment]
This does sound good, as I have no experience with debian packaging. PR would be great, thanks!

**Comment by ensonic** [comment]
The packages would need to be sent to dlech via email right now. If you want I can do that for the current release.

**Comment by ddemidov** [comment]
Does the script need to be run inside either ev3 brick or cross-compilation environment? In case not, we could try to add a Travis-CI script to do the packaging automatically whenever a new tag is pushed.

**Comment by ddemidov** [comment]
It seems sending emails from Travis-CI jobs is not allowed for the reasons of spam-prevention.

**Comment by ensonic** [comment]
Yep, when I run this from the desktop I get: python-python-ev3dev_0.2.2.post1-1_amd64.deb
So we need to run this from brickstrap. This is because of the cpp extension :/

I was wondering if it would make sense in the long run to:
a) generate the full module
b) rewrite the language spec to be based on gobject introspection.

b) would be in sync with brickman and we'd get js, python, vala, lua, haskell, ... from that.

**Comment by ddemidov** [comment]
I am sorry, I did not understand neither (a) nor (b) (just returned from a trip, so may be my brain is still damaged). What exactly do you mean by generating the full module? And by rewriting the spec to be based on gobject introspection?

**Comment by ensonic** [comment]
If python-ev3dev would be pure python (no c++ code), we can have an architecture independent package (no need to build in brickstrap). That would be what I mean with option a).

Regarding option b) - ev3devKit is written in vala. This compiles to a gobject base c library. Now gobject introspection can add all kind of language support for such a library. For python e.g. one just imports the library and the python classes are generated on the fly. Maybe we can chat with dlech about this in #ev3dev irc.

**Comment by ddemidov** [comment]
Ok, then (a) is what's @rhempel is working on in his [pure-python](https://github.com/ev3dev/ev3dev-lang/tree/pure-python) branch.

Regarding (b), how good the generated interface would be? Would gobject programming patterns be imposed on all the other bindings?

**Comment by ensonic** [comment]
is pure-python going to be a drop-in replacement?

Regarding gobject-introspection, if the library is writtign with bindings in mind, one gets nice bindings in return. Here is an example for python and gtk: http://python-gtk-3-tutorial.readthedocs.org/en/latest/introduction.html

**Comment by antonvh** [comment]
I had trouble subclassing the boost.python stuff. I hope that will be better in pure-python. Haven't figured out how to switch, yet. 
This doesn't work anyway:
```
class PIDMotor(ev3dev.motor):
     def __init__(self, motor_port):
         ev3dev.motor.__init__(motor_port)
```

**Comment by ddemidov** [comment]
@antonvh, I think you need to use `Super` to init the subclass. See https://github.com/ddemidov/ev3dev-lang-python/blob/master/ev3dev/__init__.py#L345-L351 for an example.

**Comment by ddemidov** [comment]
@ensonic, it looks like pure-python can be a drop-in replacement if @rhempel and I agree on a couple of class name changes. Also see the tail of discussion here: https://github.com/ev3dev/ev3dev-lang/issues/3 and examples here: https://gist.github.com/ddemidov/e27fdf63f3ff6bb98dcf.

E.g. Ralf calls his `motor` class `Motor`. Otherwise the code is the same. It does comply better with [pep 0008](https://www.python.org/dev/peps/pep-0008/), but the lowercase convention is used for C-based extensions. I guess I could change my class names to CamelCase.

**Comment by rhempel** [comment]
My suggestion is that if we need to introduce breaking changes, we do it now, and we do it to acheive better compliance with pep 0008, the whole point of the binding generator is to be flexible enough to make class and object naming conform to the idioms of the target language.

I'll try and get my pure-python branch updated so with a few more tweaks so that others can have a good review of the implementation.

One thing I did was to add an optional parameter for the device filename when a corresponding portname is not available, for example the LED devices.

**Comment by ddemidov** [comment]
@rhempel, I can capitalize my class names and push a new release when @dlech and @ensonic are happy with the state of debian packaging scripts. Btw, PEP0008 [says](https://www.python.org/dev/peps/pep-0008/#class-names) that class names should use `CapitalizedWords` convention, unlike your `EV3_Device` or `DC_Motor` (these are [called](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) "`Capitalized_Words_With_Underscores` (ugly!)"). Would you change the naming as well, so that we converge to the same interface?

**Comment by rhempel** [comment]
I am happy to converge on the most Pythonic way of doing things - I'll fix the class names tonight as well

**Comment by rhempel** [comment]
Decision time - `EV3Device` or `Ev3Device` - I'm leaning towards `EV3Device` but am willing to listen to good arguments against it. Besides, it's an easy change when you have `autogen`!

**Comment by dlech** [comment]
I've actually give this a bit of thought lately. My conclusion has been that when writing in camelCase or PascalCase, acronyms should be written with the first letter capitalized only. I find that it makes it easier to read and is essential when you have two or more acronyms back-to-back. I've actually gone through ev3devKit recently changed it to follow this.

`Ev3Device` does look kind of weird because of the `3` in there, but for consistency with everything else, it is my preferred choice.

**Comment by ddemidov** [comment]
Why not just Device? You are already in ev3dev namespace. Also, this should
work for rpi as well.

On Tue, Sep 29, 2015, 03:10 David Lechner <notifications@github.com> wrote:

> I've actually give this a bit of thought lately. My conclusion has been
> that when writing in camelCase or PascalCase, acronyms should be written
> with the first letter capitalized only. I find that it makes it easier to
> read and is essential when you have two or more acronyms back-to-back. I've
> actually gone through ev3devKit recently changed it to follow this.
>
> Ev3Device does look kind of weird because of the 3 in there, but for
> consistency with everything else, it is my preferred choice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddemidov/ev3dev-lang-python/issues/13#issuecomment-143907878>
> .
>
-- 

Cheers,
Denis

**Comment by rhempel** [comment]
You see, this is why we have reviews. Now, if we were all in one office we could do this over lunch or coffee :-) I'll let this sink in overnight...
